development:
  clients:
    default:
      database: base_development
      hosts:
        - localhost
test:
  clients:
    default:
      database: base_test
      hosts:
        - localhost
production:
  clients:
    default:
      database: base
      hosts:
        - localhost